Reflect the reality for the focus event order
w3c/uievents pull request #290
Opened 2021-01-23 23:43 UTC by saschanaz

Closes #88

The following tasks have been completed:

 * [x] Confirmed there are no ReSpec/BikeShed errors or warnings.
 * [x] Modified Web platform tests (link to pull request): https://github.com/web-platform-tests/wpt/pull/26401

Implementation commitment:

 * [x] WebKit: Already implemented
 * [x] Chromium: Already implemented
 * [x] Gecko: Already implemented

2021-09-15 00:21 UTC, garykac requested changes
Can you remove or update the `index.html` file in this PR?

Removing it might be easier, and then we can follow-up with a separate cl that runs `bikeshed` to regenerate the HTML

2021-09-15 00:23 UTC, saschanaz commented
index.html doesn't exist anymore so removing is really the only option.

2021-09-15 00:55 UTC, garykac commented
> index.html doesn't exist anymore so removing is really the only option.

Oh, I forgot we removed it completely.

2021-12-09 00:52 UTC, saschanaz commented
Sorry for the long delay, now this should be ready for reviews. cc @masayuki-nakano

2022-03-20 09:08 UTC, danburzo commented on sections/event-types.txt
> +			type. This event type is similar to [=blur=], but does not bubble.
A small typo: 

```suggestion
			type. This event type is similar to [=blur=], but does bubble.
```

2022-03-20 09:10 UTC, danburzo commented on sections/event-types.txt
> +			not bubble.
Small typo: 

```suggestion
			bubble.
```

2023-05-09 21:59 UTC, garykac approved these changes

2023-05-09 21:59 UTC, merged